#!/usr/bin/expect  

set timeout 30

spawn ssh -l root [lrange $argv 0 0]

expect {
"yes/no" {send "yes\r";exp_continue}
"password:" {send "Pass1234\r"}
}
send "Pass1234\r"
expect "*$ "
send -- "scp liqian@192.168.253.130:/usr/mabo/get_info.sh /usr/mabo/"
expect "*?assword:*"
send -- "liqian\r"
expect "*$ " 
send -- "bash get_info.sh [lrange $argv 0 0]\r"
expect "*$ " 
send -- "scp /usr/mabo/info_*.txt liqian@192.168.253.130:/usr/mabo\r"
expect "*?assword:*"
send -- "liqian\r"
expect "*$ " 
send -- "exit\r"
expect eof
